# Generated by Django 6.1.1 on 2026-09-03 16:57

import django.core.validators
import django.db.models.deletion
import profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('company_description', models.TextField(blank=True, verbose_name='Company Description')),
                ('industry', models.CharField(help_text='Industry sector (e.g. Information Technology, Finance, Healthcare)', max_length=100)),
                ('website', models.URLField(blank=True, help_text='Official company website', max_length=255, null=True)),
                ('location', models.CharField(help_text='Headquarters or branch location (e.g. Bengaluru, India)', max_length=200)),
                ('contact_email', models.EmailField(max_length=254, verbose_name='HR / Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('company_size', models.CharField(blank=True, help_text="Number of employees (e.g. '1-50', '51-200', '201-1000', '1000+')", max_length=50)),
                ('logo', models.ImageField(blank=True, help_text='Company logo image', null=True, upload_to='company_logos/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='TPO Verification Status (PENDING, APPROVED, REJECTED)', max_length=20, verbose_name='Verification Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(help_text='Academic Department (e.g. Computer Science, Mechanical)', max_length=100)),
                ('course', models.CharField(help_text='Degree/Course (e.g. B.Tech, M.Tech, MCA)', max_length=100)),
                ('year', models.PositiveIntegerField(help_text='Current Year of Study or Graduation Year (e.g. 4 or 2026)')),
                ('cgpa', models.DecimalField(decimal_places=2, help_text='Cumulative Grade Point Average (0.00 - 10.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('skills', models.TextField(blank=True, help_text='Technical & professional skills (comma-separated or list)')),
                ('resume', models.FileField(blank=True, help_text='Upload resume in PDF, DOC, or DOCX format (Max 5MB)', null=True, upload_to='resumes/', validators=[profiles.validators.validate_resume_file])),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL', max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL', max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL (Optional, e.g. https://www.instagram.com/username/)', max_length=255, null=True, validators=[profiles.validators.validate_instagram_url])),
                ('portfolio_url', models.URLField(blank=True, help_text='Personal Portfolio or Website URL', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of Birth (Optional, YYYY-MM-DD)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
