# Generated by Django 6.1.1 on 2026-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='verification_remarks',
            field=models.TextField(blank=True, help_text='Feedback or remarks by TPO during verification', verbose_name='Verification Remarks'),
        ),
    ]
