# Generated by Django 6.1.1 on 2026-09-04 05:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_companyprofile_verification_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('job_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('INTERNSHIP', 'Internship'), ('PART_TIME', 'Part Time')], default='FULL_TIME', max_length=50, verbose_name='Job Type')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Annual CTC or monthly stipend in INR', max_digits=12, null=True, verbose_name='Salary / CTC (in INR)')),
                ('job_location', models.CharField(help_text='e.g. Bengaluru, Remote, Hyderabad', max_length=150, verbose_name='Job Location')),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum CGPA required to apply (0.00 - 10.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('10.00'))], verbose_name='Minimum CGPA')),
                ('eligible_departments', models.JSONField(blank=True, default=list, help_text="List of eligible department names, e.g. ['CSE', 'IT']", verbose_name='Eligible Departments')),
                ('eligible_courses', models.JSONField(blank=True, default=list, help_text="List of eligible degrees/courses, e.g. ['B.Tech', 'M.Tech']", verbose_name='Eligible Courses')),
                ('application_deadline', models.DateTimeField(verbose_name='Application Deadline')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_TPO_APPROVAL', 'Pending TPO Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='PENDING_TPO_APPROVAL', max_length=30, verbose_name='Status')),
                ('approval_remarks', models.TextField(blank=True, default='', help_text='Feedback or remarks from TPO during approval', verbose_name='TPO Approval Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listings', to='profiles.companyprofile', verbose_name='Company Profile')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APPLIED', 'Applied'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('SELECTED', 'Selected')], default='APPLIED', max_length=30, verbose_name='Application Status')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.studentprofile', verbose_name='Student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.joblisting', verbose_name='Job Listing')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'job')},
            },
        ),
    ]
