# Generated by Django 6.1.1 on 2026-09-04 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_joblisting_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter_number', models.CharField(max_length=100, unique=True, verbose_name='Offer Letter / Reference Number')),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Annual CTC (in INR)')),
                ('joining_date', models.DateField(verbose_name='Expected Date of Joining')),
                ('offer_details', models.TextField(blank=True, default='', verbose_name='Offer Details / Terms')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Offer Status')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='profiles.jobapplication', verbose_name='Job Application')),
            ],
            options={
                'verbose_name': 'Job Offer',
                'verbose_name_plural': 'Job Offers',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_status', models.CharField(choices=[('PLACED', 'Placed'), ('WITHDRAWN', 'Withdrawn')], default='PLACED', max_length=20, verbose_name='Placement Status')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Annual CTC (in INR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_record', to='profiles.jobapplication', verbose_name='Job Application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='profiles.companyprofile', verbose_name='Company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='profiles.joblisting', verbose_name='Job Listing')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='placement_record', to='profiles.joboffer', verbose_name='Job Offer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_records', to='profiles.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Placement Record',
                'verbose_name_plural': 'Placement Records',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='Interview Round Number')),
                ('interview_type', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20, verbose_name='Interview Type')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled Date & Time')),
                ('venue', models.CharField(blank=True, default='', help_text='Required for OFFLINE interviews', max_length=255, verbose_name='Physical Venue')),
                ('meeting_link', models.URLField(blank=True, default='', help_text='Required for ONLINE interviews', max_length=500, verbose_name='Online Meeting Link')),
                ('interviewer', models.CharField(blank=True, default='', max_length=200, verbose_name='Interviewer Name / Panel')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='Interview Status')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Interview Feedback / Assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='profiles.jobapplication', verbose_name='Job Application')),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'ordering': ['round', 'scheduled_at'],
                'unique_together': {('application', 'round')},
            },
        ),
    ]
