# Generated by Django 6.1.1 on 2026-10-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_notification_placementdrive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('JOB_REVIEW_REQUIRED', 'Job review required'), ('NEW_JOB', 'New job available'), ('APPLICATION_SUBMITTED', 'Application submitted'), ('APPLICATION_SHORTLISTED', 'Application shortlisted'), ('INTERVIEW_SCHEDULED', 'Interview scheduled'), ('OFFER_ISSUED', 'Offer issued'), ('PLACEMENT_CONFIRMED', 'Placement confirmed'), ('PLACEMENT_STATUS_UPDATED', 'Placement status updated')], max_length=32),
        ),
    ]
